controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
app_secret_hash:
    path: /secret/hash
    controller: App\Controller\SecretHashController::hash


