controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
app_secret_hash:
    path: /secret/hash
    controller: App\Controller\SecretHashController::hash
    
        
# homepage:
#     path: /
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#     defaults:
#         path: /Secret
#         permanent: false
